### ISSUE TITLE
On some websites, the font turns black.

### ISSUE THREAD

**Issue by Alphabet1226** [mlijanto/scrollbar-of-contents#12]
https://www.ruanyifeng.com/blog/2020/08/ransomware.html
![image](https://user-images.githubusercontent.com/51783873/91677448-4a642700-eb75-11ea-97c0-c687a7cfafba.png)

**Comment by mlijanto** [comment]
@Alphabet1226 This issue is now fixed and an updated version is published on the Web Store. Thanks for reporting this bug!
